# Generated by Django 6.0.2 on 2026-03-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0002_college_course_faculty_marksheet_role_student_subject_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanAmount', models.CharField(max_length=50)),
                ('interestRate', models.CharField(max_length=50)),
                ('issueDate', models.DateField(max_length=20)),
            ],
            options={
                'db_table': 'sos_loan',
            },
        ),
    ]
