# Generated by Django 6.0.2 on 2026-03-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0003_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=50)),
                ('membershipType', models.CharField(max_length=30)),
                ('startDate', models.DateField(max_length=20)),
                ('endDate', models.DateField(max_length=20)),
            ],
            options={
                'db_table': 'sos_gym',
            },
        ),
    ]
